# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cryptex < Formula
  desc "Secure your secrets with a powerful and easy to use CLI application
"
  homepage "https://github.com/mas2020-golang/cryptex"
  version "0.2.0-dev.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/mas2020-golang/cryptex/releases/download/v0.2.0-dev.2/cryptex_0.2.0-dev.2_Darwin-arm64.tar.gz"
      sha256 "b995d8d4254cd2ee4a5e585ca78b53f7136a69357982c104a45e7ef702939a89"

      def install
        bin.install "cryptex"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mas2020-golang/cryptex/releases/download/v0.2.0-dev.2/cryptex_0.2.0-dev.2_Darwin-x86_64.tar.gz"
      sha256 "7edfd365399b16cee6b57f7a49d8c08e64e903fceba192d8497c6b1b447bbedf"

      def install
        bin.install "cryptex"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mas2020-golang/cryptex/releases/download/v0.2.0-dev.2/cryptex_0.2.0-dev.2_Linux-x86_64.tar.gz"
      sha256 "4698aab8ef268aa4e3ee98e0e91a4155f89ac108c75e08cf08cd1f4c109cfa4a"

      def install
        bin.install "cryptex"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mas2020-golang/cryptex/releases/download/v0.2.0-dev.2/cryptex_0.2.0-dev.2_Linux-arm64.tar.gz"
      sha256 "ae3cbb71e90127daa406890689d4f2d29784813b5c8d90d34f51e0b5d8b97393"

      def install
        bin.install "cryptex"
      end
    end
  end
end
